language: node_js
branches:
  only:
    - v0.1
cache:
  directories:
    - node_modules
before_script:
  - npm i firebase-tools
script: 
  -firebase deploy --only functions 
notifications:
  email:
    on_failure: change
    on_success: change