language: node_js
mode_js: 
  - "7"
branches:
  only:
    - v0.1
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script: 
  -firebase deploy --only functions 
notifications:
  email:
    on_failure: change
    on_success: change